# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Projects Grid"
  description: Grid of project cards with external links
  icon: "grid_view"
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: "Projects"
  description_html: ""
  show_projects: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: "Projects"
  description_html: "<p>Check out my recent work</p>"
  show_projects: true

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: